/**
 * PROJECT AS ABOVE, SO BELOW
 * Module: OTU Importer
 * Description: Handles the "Import the Imperium" feature.
 *   - Loads the sector list from the local chart index
 *   - Presents a modal for sector selection and slot assignment
 *   - Reads each selected sector from the local chart snapshot
 *   - Feeds the result into the existing importT5Tab parser
 *
 * Sean Protocol: Zero RPG logic here. Pure orchestration and UI.
 */

(function () {
    'use strict';

    /**
     * Sector list is provided by js/imperium_data.js (auto-generated by convert_imperium.ps1).
     * Re-run convert_imperium.ps1 whenever sectors/imperium.tsv changes.
     */
    function getImperiumSectors() {
        if (!window.IMPERIUM_SECTORS || window.IMPERIUM_SECTORS.length === 0) {
            throw new Error('Sector list not loaded. Run convert_imperium.ps1 to generate js/imperium_data.js.');
        }
        return window.IMPERIUM_SECTORS;
    }

    /**
     * Reads one sector from the local chart snapshot.
     */
    async function readSnapshot(name) {
        if (!window.UniverseSnapshot) throw new Error('The chart snapshot is not loaded.');
        return window.UniverseSnapshot.load(name);
    }

    /**
     * Reads sector metadata XML from the local snapshot.
     * Non-fatal: logs a warning and returns null so the import continues.
     */
    async function fetchAndCacheMetadata(name) {
        try {
            const data = await readSnapshot(name);
            return data.metadataXml || null;
        } catch (err) {
            console.warn(`[OTU Importer] No metadata for "${name}": ${err.message}`);
            return null;
        }
    }

    async function fetchAndCacheUniverseMetadata(name) {
        return fetchAndCacheMetadata(name);
    }

    /**
     * Allegiance code → name from the local chart list.
     * Returns { names, live }. live stays false: nothing is requested.
     */
    async function fetchAllegianceNames() {
        const names = window.UNIVERSE_ALLEGIANCES || {};
        return { names, live: false };
    }

    function applyAllegianceNames(names) {
        const touched = [];
        if (!names) return touched;
        hexStates.forEach((state, id) => {
            if (!state || !state.allegiance) return;
            const name = names[state.allegiance];
            if (name) {
                state.allegianceName = name;
                touched.push(id);
            }
        });
        return touched;
    }

    // Traveller Map Tags for the year-1105 chart, keyed "x,y".
    let sectorReviewByCoord = null;
    let sectorReviewLoad = null;

    function describeSectorReview(tags) {
        const text = (tags || '').trim();
        if (!text) return null;
        if (/\bOfficial\b/i.test(text)) return { label: 'Official', tone: 'official', title: text };
        if (/InReview/i.test(text)) return { label: 'In review', tone: 'review', title: text };
        if (/Preserve/i.test(text)) return { label: 'Preserve', tone: 'preserve', title: text };
        if (/Apocryphal/i.test(text)) return { label: 'Apocrypha', tone: 'apocrypha', title: text };
        if (/Unreviewed/i.test(text)) return { label: 'Unreviewed', tone: 'unreviewed', title: text };
        if (text === 'OTU') return { label: 'OTU', tone: 'otu', title: 'OTU, not marked official or in review' };
        return { label: text, tone: 'otu', title: text };
    }
    window.describeSectorReview = describeSectorReview;

    function reviewSummary(tagList) {
        const counts = new Map();
        tagList.forEach(tags => {
            const described = describeSectorReview(tags);
            const label = described ? described.label : 'Unknown';
            counts.set(label, (counts.get(label) || 0) + 1);
        });
        const order = ['Official', 'In review', 'Unreviewed', 'OTU', 'Preserve', 'Apocrypha'];
        return [...counts.keys()]
            .sort((a, b) => (order.indexOf(a) === -1 ? 99 : order.indexOf(a)) - (order.indexOf(b) === -1 ? 99 : order.indexOf(b)))
            .map(label => `${counts.get(label)} ${label.toLowerCase()}`)
            .join(' · ');
    }

    function paintReviewPill(el, tags, pending) {
        el.className = 'otu-review';
        if (pending) {
            el.classList.add('otu-review-pending');
            el.textContent = '…';
            el.title = 'Checking review status';
            return;
        }
        const described = describeSectorReview(tags);
        if (!described) {
            el.textContent = '';
            el.title = '';
            return;
        }
        el.classList.add('otu-review-' + described.tone);
        el.textContent = described.label;
        el.title = described.title;
    }

    async function fetchSectorReviewMap() {
        const byCoord = {};
        (window.UNIVERSE_SECTORS || []).forEach(sector => {
            if (sector.tags) byCoord[`${sector.x},${sector.y}`] = sector.tags;
        });
        (window.UNIVERSE_INDEX && window.UNIVERSE_INDEX.sectors || []).forEach(sector => {
            if (sector.tags) byCoord[`${sector.x},${sector.y}`] = sector.tags;
        });
        return byCoord;
    }

    function loadSectorReview() {
        if (sectorReviewByCoord) return Promise.resolve(sectorReviewByCoord);
        if (!sectorReviewLoad) {
            sectorReviewLoad = fetchSectorReviewMap().then(map => {
                sectorReviewByCoord = map;
                return map;
            }).catch(err => {
                sectorReviewLoad = null;
                throw err;
            });
        }
        return sectorReviewLoad;
    }

    function rememberSectorReview(slotNum, x, y, byCoord) {
        if (!byCoord || slotNum == null || !Number.isFinite(slotNum)) return;
        const tags = byCoord[`${x},${y}`];
        if (!tags) return;
        if (!window.sectorReview) window.sectorReview = {};
        window.sectorReview[slotNum] = tags;
    }

    function fillImperiumReview(sectors) {
        const summary = document.getElementById('otu-review-summary');
        if (summary) summary.textContent = 'Checking review status…';
        loadSectorReview().then(byCoord => {
            const modal = document.getElementById('otu-import-modal');
            if (!modal || modal.style.display === 'none') return;
            document.querySelectorAll('#otu-sector-list .otu-review').forEach(el => {
                const sector = sectors[parseInt(el.dataset.idx, 10)];
                paintReviewPill(el, sector ? byCoord[`${sector.x},${sector.y}`] : '', false);
            });
            if (summary) summary.textContent = reviewSummary(sectors.map(s => byCoord[`${s.x},${s.y}`] || ''));
        }).catch(err => {
            if (summary) summary.textContent = 'Review status unavailable';
            console.warn(`[OTU Importer] Review status failed: ${err.message}`);
        });
    }

    function fillUniverseReview(sectors) {
        const summary = document.getElementById('universe-review-summary');
        if (!summary) return;
        summary.textContent = 'Checking review status…';
        loadSectorReview().then(byCoord => {
            const modal = document.getElementById('universe-import-modal');
            if (!modal || modal.style.display === 'none') return;
            summary.textContent = reviewSummary(sectors.map(s => byCoord[`${s.x},${s.y}`] || ''));
        }).catch(err => {
            summary.textContent = 'Review status unavailable';
            console.warn(`[OTU Importer] Review status failed: ${err.message}`);
        });
    }

    /**
     * Clears all in-memory data for one sector slot before a re-import.
     * Removes hex states, the sector name, and border hex assignments.
     * Routes are handled separately (the metadata pass wipes Route 1 globally).
     * DB consistency is guaranteed by the syncAllHexes() call after the import loop.
     */
    function clearSectorSlotData(slotNum) {
        const prefix = slotNum + '-';
        for (const hexId of hexStates.keys()) {
            if (hexId.startsWith(prefix)) hexStates.delete(hexId);
        }
        delete window.sectorNames[slotNum];
        if (window.sectorReview) delete window.sectorReview[slotNum];
        if (typeof clearSubsectorNamesForSector === 'function') {
            clearSubsectorNamesForSector(slotNum);
        }
        if (window.hexBorderAssignments) {
            for (const hexId of window.hexBorderAssignments.keys()) {
                if (hexId.startsWith(prefix)) window.hexBorderAssignments.delete(hexId);
            }
        }
    }

    /**
     * Read the four import-option checkboxes from a modal by element ID.
     * Falls back to true for any missing element so old call sites stay safe.
     */
    function readImportOptions(sectorElId, routesElId, bordersElId, regionsElId) {
        const checked = id => { const el = document.getElementById(id); return el ? el.checked : true; };
        return {
            importSector:  checked(sectorElId),
            importRoutes:  checked(routesElId),
            importBorders: checked(bordersElId),
            importRegions: checked(regionsElId),
        };
    }

    /**
     * Open the Import the Imperium modal.
     */
    function openImperiumModal() {
        try {
            const sectors = getImperiumSectors();
            renderModal(sectors);
            fillImperiumReview(sectors);
        } catch (err) {
            alert(`Failed to load sector list: ${err.message}`);
        }
    }

    /** Build and display the modal sector list. */
    function renderModal(sectors) {
        const list = document.getElementById('otu-sector-list');
        list.innerHTML = '';

        sectors.forEach((sector, idx) => {
            const row = document.createElement('label');
            row.className = 'otu-sector-row';
            row.style.cssText = [
                'display:flex', 'align-items:center', 'gap:8px',
                'padding:6px 10px', 'border-radius:4px',
                'border-left:3px solid transparent',
                'cursor:pointer', 'transition:background 0.15s, border-color 0.15s',
                'background:#0d1117'
            ].join(';');

            row.innerHTML = `
                <input type="checkbox" class="otu-sector-check" data-idx="${idx}" checked
                    style="flex-shrink:0; cursor:pointer; accent-color:#66fcf1;">
                <span class="otu-sector-name"
                    style="color:#c5c6c7; font-size:0.85rem; white-space:nowrap;">${sector.name}</span>
                <span class="otu-review otu-review-pending" data-idx="${idx}" title="Checking Traveller Map review status">…</span>
                <span style="flex:1; border-bottom:1px dotted #2a3a3a; margin:0 4px; height:1px; align-self:center;"></span>
                <input type="text" class="otu-sector-slot" value="${sector.defaultSlot}"
                    maxlength="2" size="2"
                    style="width:32px; padding:2px 4px; background:#1f2833; border:1px solid #45a29e;
                           color:#66fcf1; font-family:'Courier New',monospace; font-size:0.85rem;
                           text-align:center; text-transform:uppercase; border-radius:3px;"
                    onclick="event.stopPropagation();">
            `;

            // Highlight row on hover
            row.addEventListener('mouseenter', () => {
                row.style.background = '#1a2535';
                row.style.borderLeftColor = '#45a29e';
            });
            row.addEventListener('mouseleave', () => {
                row.style.background = '#0d1117';
                row.style.borderLeftColor = 'transparent';
            });

            list.appendChild(row);
        });

        // Reset select-all to checked
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) selectAll.checked = true;

        document.getElementById('otu-import-modal').style.display = 'flex';
    }

    /** Close the modal. */
    function closeModal() {
        document.getElementById('otu-import-modal').style.display = 'none';
    }

    /**
     * Pre-flight check, then fetch and import each selected sector in sequence.
     */
    async function runImport() {
        const opts = readImportOptions('otu-opt-sector', 'otu-opt-routes', 'otu-opt-borders', 'otu-opt-regions');
        opts.importSystemData = document.getElementById('otu-opt-system-data')?.checked ?? false;
        const needsMeta = opts.importRoutes || opts.importBorders || opts.importRegions;

        const rows = document.querySelectorAll('.otu-sector-row');
        const selected = [];

        const sectors = getImperiumSectors();
        rows.forEach((row, idx) => {
            const cb = row.querySelector('.otu-sector-check');
            const slotInput = row.querySelector('.otu-sector-slot');
            const slot = (slotInput ? slotInput.value.trim() : '').toUpperCase();
            if (cb && cb.checked && slot) {
                selected.push({ name: sectors[idx].name, slot });
            }
        });

        if (selected.length === 0) {
            alert('No sectors selected.');
            return;
        }

        closeModal();

        const importLabel = selected.length === 1 ? selected[0].name : (selected.length + ' sectors');
        let importSlot = null;
        if (window.Saves) importSlot = await window.Saves.beforeBulk('Import ' + importLabel);
        try {
        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

        opts.allegianceNames = {};
        let reviewByCoord = null;
        try { reviewByCoord = await loadSectorReview(); } catch (e) { reviewByCoord = null; }
        const allegFetch = await fetchAllegianceNames();
        Object.assign(opts.allegianceNames, allegFetch.names);

        // Build coord lookup for cross-sector route resolution.
        // Only include sectors the user actually imported — pre-loading all sectors
        // caused routes to unimported neighbours to resolve to wrong hexIds on canvas.
        const coordLookup = new Map();
        selected.forEach(sel => {
            const match = sectors.find(s => s.name === sel.name);
            if (match) coordLookup.set(`${match.x},${match.y}`, sectorSlotToNumber(sel.slot));
        });

        const sectorMetas  = [];
        const metaFailures = [];
        for (let i = 0; i < selected.length; i++) {
            const { name, slot } = selected[i];
            let tsvFromCache = false;

            if (opts.importSector) {
                try {
                    if (typeof showToast === 'function') {
                        showToast(`Importing ${name} into slot ${slot}… (${i + 1} of ${selected.length})`);
                    }
                    const slotNum = (typeof sectorSlotToNumber === 'function') ? sectorSlotToNumber(slot) : parseInt(slot, 10);
                    if (!Number.isFinite(slotNum) || slotNum < 1) throw new Error('Sector slot "' + slot + '" is not a slot on this map.');
                    const data = await window.UniverseSnapshot.adopt(name, slotNum);
                    const placed = sectors.find(s => s.name === name);
                    if (!isNaN(slotNum) && placed) rememberSectorReview(slotNum, placed.x, placed.y, reviewByCoord);
                    if (needsMeta) {
                        if (data.metadataXml && placed) {
                            sectorMetas.push({ name, metaXml: data.metadataXml, slotNum: sectorSlotToNumber(slot), x: placed.x, y: placed.y });
                        } else metaFailures.push(name);
                    }
                } catch (err) {
                    alert(`Failed to import "${name}": ${err.message}`);
                }
            }

            if (needsMeta && !opts.importSector) {
                const sectorInfo = sectors.find(s => s.name === name);
                if (typeof showToast === 'function') showToast(`Fetching metadata for ${name}…`);
                const metaXml = await fetchAndCacheMetadata(name);
                if (metaXml && sectorInfo) {
                    sectorMetas.push({ name, metaXml, slotNum: sectorSlotToNumber(slot), x: sectorInfo.x, y: sectorInfo.y });
                } else if (!metaXml) {
                    metaFailures.push(name);
                }
            }
        }

        if (needsMeta) {
            // Wipe the X-boat slot and any allegiance slots this import owns.
            // Trade routes and hand-drawn slots stay.
            if (opts.importRoutes && window.sectorRoutes) {
                window.sectorRoutes = window.sectorRoutes.filter(r =>
                    r.routeId !== 1 && !(r.groupId && String(r.groupId).startsWith('otu-route:')));
            }

            // Parse all routes/borders in a single pass after every sector is loaded,
            // so cross-sector routes can resolve both endpoints correctly.
            // Yield between sectors to keep the tab responsive.
            if (typeof parseAndAddOtuRoutes === 'function') {
                for (const m of sectorMetas) {
                    parseAndAddOtuRoutes(m.name, m.metaXml, m.slotNum, m.x, m.y, coordLookup, opts);
                    await delay(0);
                }
            }
            if (window.dbManager) window.dbManager.saveSubsectorNames?.();
            if (opts.importRoutes) {
                if (typeof window.ensureFreeRouteSlot === 'function') window.ensureFreeRouteSlot();
                if (window.dbManager) {
                    window.dbManager.saveRouteDefinitions?.();
                    window.dbManager.saveRoutes?.();
                }
                if (typeof window.renderRouteWindow === 'function') window.renderRouteWindow();
            }
            if (typeof window.sortAndTrimBorderDefinitions === 'function') window.sortAndTrimBorderDefinitions();
            if (typeof window.renderBorderWindow === 'function') window.renderBorderWindow();
        }

        const namedIds = applyAllegianceNames(opts.allegianceNames) || [];
        const systemIds = (opts.importSystemData && typeof applyOtuSystemData === 'function') ? (applyOtuSystemData() || []) : [];

        // Post-processing deferred from bulkMode importT5Tab calls — run once here,
        // after allegiance names have been written onto the hexes.
        if (opts.importSector) {
            if (typeof window.reapplyAllRules === 'function') window.reapplyAllRules();
            if (typeof window.applyActiveFilters === 'function') window.applyActiveFilters();
            const touched = namedIds.concat(systemIds);
            if (typeof markChanged === 'function') markChanged('Import ' + importLabel, { hexIds: touched, skipAutoslot: true });
            if (window.dbManager) await window.dbManager.replaceWorkingCopy();
        }

        requestAnimationFrame(draw);

        if (typeof showToast === 'function' && opts.importSector) {
            showToast('Imported ' + importLabel + '.', 6000);
        }
        if (metaFailures.length > 0 && typeof showToast === 'function') {
            const preview = metaFailures.slice(0, 3).join(', ') + (metaFailures.length > 3 ? `… (+${metaFailures.length - 3} more)` : '');
            showToast(`${metaFailures.length} metadata file(s) missing (no borders/routes): ${preview}`, 6000);
        }
        } finally {
            if (importSlot && window.Saves) window.Saves.endBulk();
        }
    }

    // =========================================================================
    // IMPORT THE UNIVERSE
    // =========================================================================

    function getUniverseSectors() {
        if (!window.UNIVERSE_SECTORS || window.UNIVERSE_SECTORS.length === 0) {
            throw new Error('Universe sector list not loaded. Run convert_universe.ps1 to generate js/universe_data.js.');
        }
        return window.UNIVERSE_SECTORS;
    }

    /** Open the Universe import modal, pre-filling the sector count. */
    function openUniverseModal() {
        let sectors;
        try {
            sectors = getUniverseSectors();
        } catch (err) {
            alert(`Cannot import: ${err.message}`);
            return;
        }
        const countEl = document.getElementById('universe-modal-sector-count');
        if (countEl) countEl.textContent = sectors.length;
        document.getElementById('universe-import-modal').style.display = 'flex';
        fillUniverseReview(sectors);
    }

    /** Close the Universe import modal. */
    function closeUniverseModal() {
        document.getElementById('universe-import-modal').style.display = 'none';
    }

    /**
     * Bulk-imports every sector in UNIVERSE_SECTORS into a freshly resized 16×8 canvas.
     * Called after the user confirms in the modal. Clears all existing data.
     */
    async function executeUniverseImport(opts) {
        const needsMeta = opts.importRoutes || opts.importBorders || opts.importRegions;

        let sectors;
        try {
            sectors = getUniverseSectors();
        } catch (err) {
            alert(`Cannot import: ${err.message}`);
            return;
        }

        let importSlot = null;
        if (window.Saves) importSlot = await window.Saves.beforeBulk('Import universe');
        const bulkHexIds = [];
        try {
        if (window.dbManager) await window.dbManager.clearDB();

        gridWidth  = 16;
        gridHeight = 8;
        hexStates.clear();
        window.overlayHexes = new Set();
        window.overlayBase = null;
        window.sectorNames        = {};
        window.sectorReview       = {};
        window.subsectorNames     = {};
        window.sectorRoutes       = [];
        window.routeDefinitions   = (typeof getDefaultRouteDefinitions === 'function') ? getDefaultRouteDefinitions() : [];
        selectedHexes.clear();
        window.hexBorderAssignments = new Map();
        window.borderPaths          = new Map();
        window.regionPaths          = new Map();
        window.borderDefinitions    = (typeof getDefaultBorderDefinitions === 'function') ? getDefaultBorderDefinitions() : [];
        window.regionDefinitions    = (typeof getDefaultRegionDefinitions === 'function') ? getDefaultRegionDefinitions() : [];

        centerCameraOnGrid();
        requestAnimationFrame(draw);

        // Persist the new grid dimensions immediately.
        if (window.dbManager) window.dbManager.saveGridDimensions();

        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
        let errorCount = 0;

        opts.allegianceNames = {};
        let reviewByCoord = null;
        try { reviewByCoord = await loadSectorReview(); } catch (e) { reviewByCoord = null; }
        const allegFetch = await fetchAllegianceNames();
        Object.assign(opts.allegianceNames, allegFetch.names);

        // Build coord lookup from all universe sectors using their default slots.
        const coordLookup = new Map();
        sectors.forEach(s => coordLookup.set(`${s.x},${s.y}`, parseInt(s.defaultSlot, 10)));

        const universeMetas = [];
        const metaFailures = [];
        for (let i = 0; i < sectors.length; i++) {
            const { name, defaultSlot, x, y } = sectors[i];
            let tsvFromCache = false;

            const isMixonForeven = opts.mixonForeven && name === 'Foreven';

            if (opts.importSector) {
                try {
                    if (isMixonForeven) {
                        // Use the embedded JS constant — no fetch needed (avoids CORS on file://).
                        if (!window.FOREVEN_MIXON_TSV) throw new Error('FOREVEN_MIXON_TSV not loaded. Run convert_foreven_mixon.ps1.');
                        tsvFromCache = true; // treat as always-available, no API delay needed

                        if (typeof showToast === 'function') {
                            showToast(`Importing Foreven (Mixon) into Slot ${defaultSlot}… [embedded]`);
                        }

                        const text = window.FOREVEN_MIXON_TSV;

                        if (typeof importT5Tab === 'function') {
                            const forevenIds = await importT5Tab(text, 'Foreven', defaultSlot, true);
                            if (Array.isArray(forevenIds)) bulkHexIds.push(...forevenIds);
                        } else {
                            throw new Error('importT5Tab not available');
                        }

                        const slotNum = parseInt(defaultSlot, 10);
                        if (!isNaN(slotNum)) {
                            window.sectorNames[slotNum] = 'Foreven';
                            rememberSectorReview(slotNum, x, y, reviewByCoord);
                        }
                    } else {
                        if (typeof showToast === 'function') {
                            showToast(`Importing ${name} into slot ${defaultSlot}… (${i + 1} of ${sectors.length})`);
                        }
                        const data = await window.UniverseSnapshot.adopt(name, defaultSlot);
                        const slotNum = parseInt(defaultSlot, 10);
                        if (!isNaN(slotNum)) rememberSectorReview(slotNum, x, y, reviewByCoord);
                        if (needsMeta) {
                            if (data.metadataXml) universeMetas.push({ name, metaXml: data.metadataXml, slotNum, x, y });
                            else metaFailures.push(name);
                        }
                    }
                } catch (err) {
                    console.warn(`[Universe Import] Failed to import "${name}": ${err.message}`);
                    errorCount++;
                }

            }

            if (needsMeta && (isMixonForeven || !opts.importSector)) {
                if (isMixonForeven) {
                    // Use the locally embedded Foreven XML.
                    if (window.FOREVEN_MIXON_XML) {
                        universeMetas.push({ name: 'Foreven', metaXml: window.FOREVEN_MIXON_XML, slotNum: parseInt(defaultSlot, 10), x, y });
                    }
                } else {
                // Fetch and cache metadata, but defer parsing until all sectors are loaded.
                if (typeof showToast === 'function') showToast(`Fetching metadata for ${name}…`);
                const metaXml = await fetchAndCacheUniverseMetadata(name);
                if (metaXml) {
                    universeMetas.push({ name, metaXml, slotNum: parseInt(defaultSlot, 10), x, y });
                } else if (needsMeta) {
                    metaFailures.push(name);
                }
                } // end else (not isMixonForeven)
            }
        }

        if (needsMeta && typeof parseAndAddOtuRoutes === 'function') {
            // Parse all routes/borders in a single pass after every sector is loaded,
            // so cross-sector routes can resolve both endpoints correctly.
            // Yield to the browser between sectors to keep the tab responsive.
            if (typeof showToast === 'function') showToast(`Processing metadata for ${universeMetas.length} sectors…`);
            for (const m of universeMetas) {
                parseAndAddOtuRoutes(m.name, m.metaXml, m.slotNum, m.x, m.y, coordLookup, opts);
                await delay(0);
            }
            if (window.dbManager) window.dbManager.saveSubsectorNames?.();
            if (opts.importRoutes) {
                if (typeof window.ensureFreeRouteSlot === 'function') window.ensureFreeRouteSlot();
                if (window.dbManager) {
                    window.dbManager.saveRouteDefinitions?.();
                    window.dbManager.saveRoutes?.();
                }
                if (typeof window.renderRouteWindow === 'function') window.renderRouteWindow();
            }
            if (typeof window.sortAndTrimBorderDefinitions === 'function') window.sortAndTrimBorderDefinitions();
            if (typeof window.renderBorderWindow === 'function') window.renderBorderWindow();
        }

        const namedIds = applyAllegianceNames(opts.allegianceNames) || [];
        const systemIds = (opts.importSystemData && typeof applyOtuSystemData === 'function') ? (applyOtuSystemData() || []) : [];

        // Post-processing deferred from bulkMode importT5Tab calls — run once here,
        // after allegiance names have been written onto the hexes.
        if (opts.importSector) {
            if (typeof window.reapplyAllRules === 'function') window.reapplyAllRules();
            if (typeof window.applyActiveFilters === 'function') window.applyActiveFilters();
            const touched = bulkHexIds.concat(namedIds, systemIds);
            if (typeof markChanged === 'function') markChanged('Import universe', { hexIds: touched, skipAutoslot: true });
            if (window.dbManager) await window.dbManager.replaceWorkingCopy();
        }

        if (typeof window.renderBorderWindow === 'function') window.renderBorderWindow();
        if (typeof window.renderRegionWindow === 'function') window.renderRegionWindow();

        requestAnimationFrame(draw);

        let summary = errorCount > 0
            ? `Universe import complete. ${errorCount} sector(s) failed — see console for details.`
            : `Universe import complete! ${sectors.length} sector(s) loaded.`;
        if (metaFailures.length > 0) {
            const preview = metaFailures.slice(0, 3).join(', ') + (metaFailures.length > 3 ? `… (+${metaFailures.length - 3} more)` : '');
            summary += ` ${metaFailures.length} metadata fetch(es) failed (no borders/routes): ${preview}`;
            console.warn(`[Universe Import] Metadata fetch failed for: ${metaFailures.join(', ')}`);
        }
        if (typeof showToast === 'function') showToast(summary, 6000);
        } finally {
            if (importSlot && window.Saves) window.Saves.endBulk();
        }
    }

    /** Wire up all event listeners once the DOM is ready. */
    document.addEventListener('DOMContentLoaded', () => {
        // "Import the Imperium" settings button
        const btnImperium = document.getElementById('btn-import-imperium');
        if (btnImperium) {
            btnImperium.addEventListener('click', openImperiumModal);
        }

        // "Import the Universe" settings button — opens modal
        const btnUniverse = document.getElementById('btn-import-universe');
        if (btnUniverse) {
            btnUniverse.addEventListener('click', openUniverseModal);
        }

        // Universe modal: Submit
        const btnUniverseSubmit = document.getElementById('universe-submit');
        if (btnUniverseSubmit) {
            btnUniverseSubmit.addEventListener('click', () => {
                const mixonEl = document.getElementById('universe-opt-mixon-foreven');
                const systemDataEl = document.getElementById('universe-opt-system-data');
                closeUniverseModal();
                executeUniverseImport({
                    importSector:     true,
                    importRoutes:     true,
                    importBorders:    true,
                    importRegions:    true,
                    mixonForeven:     mixonEl ? mixonEl.checked : false,
                    importSystemData: systemDataEl ? systemDataEl.checked : false,
                });
            });
        }

        // Universe modal: Cancel
        const btnUniverseCancel = document.getElementById('universe-cancel');
        if (btnUniverseCancel) {
            btnUniverseCancel.addEventListener('click', closeUniverseModal);
        }

        // Universe modal: backdrop click closes it
        const universeModal = document.getElementById('universe-import-modal');
        if (universeModal) {
            universeModal.addEventListener('click', (e) => {
                if (e.target === universeModal) closeUniverseModal();
            });
        }

        // Modal: Submit
        const btnSubmit = document.getElementById('otu-submit');
        if (btnSubmit) btnSubmit.addEventListener('click', runImport);

        // Modal: Cancel
        const btnCancel = document.getElementById('otu-cancel');
        if (btnCancel) btnCancel.addEventListener('click', closeModal);

        // Modal: Select / Deselect All
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) {
            selectAll.addEventListener('change', (e) => {
                document.querySelectorAll('.otu-sector-check').forEach(cb => {
                    cb.checked = e.target.checked;
                });
            });
        }

        // Close modal on backdrop click
        const modal = document.getElementById('otu-import-modal');
        if (modal) {
            modal.addEventListener('click', (e) => {
                if (e.target === modal) closeModal();
            });
        }
    });

    // Expose for debugging
    window.openImperiumModal = openImperiumModal;

}());
