/**
 * PROJECT AS ABOVE, SO BELOW
 * Module: OTU Importer
 * Description: Handles the "Import the Imperium" feature.
 *   - Loads the sector list from /sectors/imperium.tsv
 *   - Presents a modal for sector selection and slot assignment
 *   - Fetches each selected sector from the travellermap API
 *   - Feeds the result into the existing importT5Tab parser
 *
 * Sean Protocol: Zero RPG logic here. Pure orchestration and UI.
 */

(function () {
    'use strict';

    /**
     * Sector list is provided by js/imperium_data.js (auto-generated by convert_imperium.ps1).
     * Re-run convert_imperium.ps1 whenever sectors/imperium.tsv changes.
     */
    function getImperiumSectors() {
        if (!window.IMPERIUM_SECTORS || window.IMPERIUM_SECTORS.length === 0) {
            throw new Error('Sector list not loaded. Run convert_imperium.ps1 to generate js/imperium_data.js.');
        }
        return window.IMPERIUM_SECTORS;
    }

    const CACHE_PREFIX = 'otu_cache_';
    const META_PREFIX  = 'otu_meta_';
    const CACHE_TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

    /**
     * Returns cached TSV text for a sector if it exists and is less than 24 hours old.
     * Returns null on a miss, an expired entry, or any storage error.
     */
    function getCachedSector(name) {
        try {
            const raw = localStorage.getItem(CACHE_PREFIX + name);
            if (!raw) return null;
            const entry = JSON.parse(raw);
            if (!entry || !entry.timestamp || !entry.data) return null;
            if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
            return entry.data;
        } catch (e) {
            return null;
        }
    }

    /**
     * Fetches raw TSV text for a sector from the travellermap API.
     * Throws on HTTP error. Shared by both cache paths.
     */
    async function fetchSectorText(name) {
        const url = `https://travellermap.com/data/${encodeURIComponent(name)}/tab?milieu=M1105`;
        const response = await fetch(url);
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        return await response.text();
    }

    /**
     * Fetches a sector, writes it to localStorage, and returns the TSV text.
     * Used by the Imperium import (small number of sectors, fits in localStorage).
     * Silently skips the cache write on QuotaExceededError so import still completes.
     */
    async function fetchAndCacheSector(name) {
        const text = await fetchSectorText(name);
        try {
            localStorage.setItem(CACHE_PREFIX + name, JSON.stringify({
                timestamp: Date.now(),
                data: text
            }));
        } catch (e) {
            console.warn(`[OTU Importer] Could not cache "${name}": ${e.message}`);
        }
        return text;
    }

    /**
     * Reads a universe sector TSV from IndexedDB. Returns the text string or null
     * on a miss, expiry, or if dbManager is unavailable.
     */
    async function getCachedUniverseSector(name) {
        if (!window.dbManager) return null;
        const entry = await window.dbManager.getTsvCache(name);
        if (!entry || !entry.data || !entry.timestamp) return null;
        if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
        return entry.data;
    }

    /**
     * Fetches a sector, writes it to the IndexedDB TSV cache, and returns the text.
     * Used by the Universe import (128 sectors, exceeds localStorage quota).
     */
    async function fetchAndCacheUniverseSector(name) {
        const text = await fetchSectorText(name);
        if (window.dbManager) await window.dbManager.putTsvCache(name, text);
        return text;
    }

    /**
     * Returns cached metadata XML for a sector, or null on miss/expiry.
     */
    function getCachedMetadata(name) {
        try {
            const raw = localStorage.getItem(META_PREFIX + name);
            if (!raw) return null;
            const entry = JSON.parse(raw);
            if (!entry || !entry.timestamp || !entry.data) return null;
            if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
            return entry.data;
        } catch (e) {
            return null;
        }
    }

    /**
     * Fetches sector metadata XML from travellermap, caches it, and returns the raw text.
     * Non-fatal: logs a warning and returns null on HTTP error so the import continues.
     */
    async function fetchAndCacheMetadata(name, x, y) {
        const url = (x !== undefined && y !== undefined)
            ? `https://travellermap.com/api/metadata?sx=${x}&sy=${y}&accept=text/xml&milieu=M1105`
            : `https://travellermap.com/api/metadata?sector=${encodeURIComponent(name)}&accept=text/xml&milieu=M1105`;
        let text;
        try {
            const response = await fetch(url);
            if (!response.ok) {
                console.warn(`[OTU Importer] Metadata fetch failed for "${name}": HTTP ${response.status}`);
                return null;
            }
            text = await response.text();
        } catch (e) {
            console.warn(`[OTU Importer] Metadata fetch error for "${name}": ${e.message}`);
            return null;
        }
        try {
            localStorage.setItem(META_PREFIX + name, JSON.stringify({
                timestamp: Date.now(),
                data: text
            }));
        } catch (e) {
            console.warn(`[OTU Importer] Could not cache metadata for "${name}": ${e.message}`);
        }
        return text;
    }

    /**
     * Reads universe metadata XML from IndexedDB. Returns text or null.
     * Keyed as 'meta:<name>' inside the shared tsvCache store.
     */
    async function getCachedUniverseMetadata(name) {
        if (!window.dbManager) return null;
        const entry = await window.dbManager.getTsvCache('meta:' + name);
        if (!entry || !entry.data || !entry.timestamp) return null;
        if (Date.now() - entry.timestamp > CACHE_TTL_MS) return null;
        return entry.data;
    }

    /**
     * Fetches sector metadata XML and writes it to IndexedDB.
     * Non-fatal: logs a warning and returns null on HTTP error.
     */
    async function fetchAndCacheUniverseMetadata(name, x, y) {
        const url = (x !== undefined && y !== undefined)
            ? `https://travellermap.com/api/metadata?sx=${x}&sy=${y}&accept=text/xml&milieu=M1105`
            : `https://travellermap.com/api/metadata?sector=${encodeURIComponent(name)}&accept=text/xml&milieu=M1105`;
        let text;
        try {
            const response = await fetch(url);
            if (!response.ok) {
                console.warn(`[OTU Importer] Metadata fetch failed for "${name}": HTTP ${response.status}`);
                return null;
            }
            text = await response.text();
        } catch (e) {
            console.warn(`[OTU Importer] Metadata fetch error for "${name}": ${e.message}`);
            return null;
        }
        if (window.dbManager) await window.dbManager.putTsvCache('meta:' + name, text);
        return text;
    }

    const ALLEG_KEY = 'otu_t5ss_allegiances';

    /**
     * One list of T5SS allegiance code → name. Cached for a day.
     * Returns { names, live } so the caller can pause after a real request.
     */
    async function fetchAllegianceNames() {
        try {
            const raw = localStorage.getItem(ALLEG_KEY);
            if (raw) {
                const entry = JSON.parse(raw);
                if (entry && entry.data && entry.timestamp && Date.now() - entry.timestamp < CACHE_TTL_MS) {
                    return { names: entry.data, live: false };
                }
            }
        } catch (e) { /* cache miss */ }
        try {
            const response = await fetch('https://travellermap.com/t5ss/allegiances');
            if (!response.ok) return { names: {}, live: false };
            const list = await response.json();
            const names = {};
            (Array.isArray(list) ? list : []).forEach(item => {
                if (item && item.Code && item.Name) names[item.Code] = item.Name;
            });
            try {
                localStorage.setItem(ALLEG_KEY, JSON.stringify({ timestamp: Date.now(), data: names }));
            } catch (e) { /* quota */ }
            return { names, live: true };
        } catch (e) {
            console.warn(`[OTU Importer] Allegiance list failed: ${e.message}`);
            return { names: {}, live: false };
        }
    }

    function applyAllegianceNames(names) {
        if (!names) return;
        hexStates.forEach(state => {
            if (!state || !state.allegiance) return;
            const name = names[state.allegiance];
            if (name) state.allegianceName = name;
        });
    }

    // Traveller Map Tags for the year-1105 chart, keyed "x,y".
    const REVIEW_KEY = 'otu_sector_review_index';
    let sectorReviewByCoord = null;
    let sectorReviewLoad = null;
    let reviewLiveAt = 0;

    function describeSectorReview(tags) {
        const text = (tags || '').trim();
        if (!text) return null;
        if (/\bOfficial\b/i.test(text)) return { label: 'Official', tone: 'official', title: text };
        if (/InReview/i.test(text)) return { label: 'In review', tone: 'review', title: text };
        if (/Preserve/i.test(text)) return { label: 'Preserve', tone: 'preserve', title: text };
        if (/Apocryphal/i.test(text)) return { label: 'Apocrypha', tone: 'apocrypha', title: text };
        if (/Unreviewed/i.test(text)) return { label: 'Unreviewed', tone: 'unreviewed', title: text };
        if (text === 'OTU') return { label: 'OTU', tone: 'otu', title: 'OTU, not marked official or in review' };
        return { label: text, tone: 'otu', title: text };
    }
    window.describeSectorReview = describeSectorReview;

    function reviewSummary(tagList) {
        const counts = new Map();
        tagList.forEach(tags => {
            const described = describeSectorReview(tags);
            const label = described ? described.label : 'Unknown';
            counts.set(label, (counts.get(label) || 0) + 1);
        });
        const order = ['Official', 'In review', 'Unreviewed', 'OTU', 'Preserve', 'Apocrypha'];
        return [...counts.keys()]
            .sort((a, b) => (order.indexOf(a) === -1 ? 99 : order.indexOf(a)) - (order.indexOf(b) === -1 ? 99 : order.indexOf(b)))
            .map(label => `${counts.get(label)} ${label.toLowerCase()}`)
            .join(' · ');
    }

    function paintReviewPill(el, tags, pending) {
        el.className = 'otu-review';
        if (pending) {
            el.classList.add('otu-review-pending');
            el.textContent = '…';
            el.title = 'Checking Traveller Map review status';
            return;
        }
        const described = describeSectorReview(tags);
        if (!described) {
            el.textContent = '';
            el.title = '';
            return;
        }
        el.classList.add('otu-review-' + described.tone);
        el.textContent = described.label;
        el.title = described.title;
    }

    async function fetchSectorReviewMap() {
        try {
            const raw = localStorage.getItem(REVIEW_KEY);
            if (raw) {
                const entry = JSON.parse(raw);
                if (entry && entry.data && entry.timestamp && Date.now() - entry.timestamp < CACHE_TTL_MS) {
                    return entry.data;
                }
            }
        } catch (e) { /* cache miss */ }
        const response = await fetch('https://travellermap.com/api/universe?milieu=M1105');
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        const data = await response.json();
        const byCoord = {};
        (data.Sectors || []).forEach(sector => {
            byCoord[`${sector.X},${sector.Y}`] = sector.Tags || '';
        });
        reviewLiveAt = Date.now();
        try {
            localStorage.setItem(REVIEW_KEY, JSON.stringify({ timestamp: Date.now(), data: byCoord }));
        } catch (e) { /* quota */ }
        return byCoord;
    }

    function loadSectorReview() {
        if (sectorReviewByCoord) return Promise.resolve(sectorReviewByCoord);
        if (!sectorReviewLoad) {
            sectorReviewLoad = fetchSectorReviewMap().then(map => {
                sectorReviewByCoord = map;
                return map;
            }).catch(err => {
                sectorReviewLoad = null;
                throw err;
            });
        }
        return sectorReviewLoad;
    }

    function rememberSectorReview(slotNum, x, y, byCoord) {
        if (!byCoord || slotNum == null || !Number.isFinite(slotNum)) return;
        const tags = byCoord[`${x},${y}`];
        if (!tags) return;
        if (!window.sectorReview) window.sectorReview = {};
        window.sectorReview[slotNum] = tags;
    }

    function fillImperiumReview(sectors) {
        const summary = document.getElementById('otu-review-summary');
        if (summary) summary.textContent = 'Checking review status…';
        loadSectorReview().then(byCoord => {
            const modal = document.getElementById('otu-import-modal');
            if (!modal || modal.style.display === 'none') return;
            document.querySelectorAll('#otu-sector-list .otu-review').forEach(el => {
                const sector = sectors[parseInt(el.dataset.idx, 10)];
                paintReviewPill(el, sector ? byCoord[`${sector.x},${sector.y}`] : '', false);
            });
            if (summary) summary.textContent = reviewSummary(sectors.map(s => byCoord[`${s.x},${s.y}`] || ''));
        }).catch(err => {
            if (summary) summary.textContent = 'Review status unavailable';
            console.warn(`[OTU Importer] Review status failed: ${err.message}`);
        });
    }

    function fillUniverseReview(sectors) {
        const summary = document.getElementById('universe-review-summary');
        if (!summary) return;
        summary.textContent = 'Checking review status…';
        loadSectorReview().then(byCoord => {
            const modal = document.getElementById('universe-import-modal');
            if (!modal || modal.style.display === 'none') return;
            summary.textContent = reviewSummary(sectors.map(s => byCoord[`${s.x},${s.y}`] || ''));
        }).catch(err => {
            summary.textContent = 'Review status unavailable';
            console.warn(`[OTU Importer] Review status failed: ${err.message}`);
        });
    }

    /**
     * Clears all in-memory data for one sector slot before a re-import.
     * Removes hex states, the sector name, and border hex assignments.
     * Routes are handled separately (the metadata pass wipes Route 1 globally).
     * DB consistency is guaranteed by the syncAllHexes() call after the import loop.
     */
    function clearSectorSlotData(slotNum) {
        const prefix = slotNum + '-';
        for (const hexId of hexStates.keys()) {
            if (hexId.startsWith(prefix)) hexStates.delete(hexId);
        }
        delete window.sectorNames[slotNum];
        if (window.sectorReview) delete window.sectorReview[slotNum];
        if (typeof clearSubsectorNamesForSector === 'function') {
            clearSubsectorNamesForSector(slotNum);
        }
        if (window.hexBorderAssignments) {
            for (const hexId of window.hexBorderAssignments.keys()) {
                if (hexId.startsWith(prefix)) window.hexBorderAssignments.delete(hexId);
            }
        }
    }

    /**
     * Read the four import-option checkboxes from a modal by element ID.
     * Falls back to true for any missing element so old call sites stay safe.
     */
    function readImportOptions(sectorElId, routesElId, bordersElId, regionsElId) {
        const checked = id => { const el = document.getElementById(id); return el ? el.checked : true; };
        return {
            importSector:  checked(sectorElId),
            importRoutes:  checked(routesElId),
            importBorders: checked(bordersElId),
            importRegions: checked(regionsElId),
        };
    }

    /**
     * Open the Import the Imperium modal.
     */
    function openImperiumModal() {
        try {
            const sectors = getImperiumSectors();
            renderModal(sectors);
            fillImperiumReview(sectors);
        } catch (err) {
            alert(`Failed to load sector list: ${err.message}`);
        }
    }

    /** Build and display the modal sector list. */
    function renderModal(sectors) {
        const list = document.getElementById('otu-sector-list');
        list.innerHTML = '';

        sectors.forEach((sector, idx) => {
            const row = document.createElement('label');
            row.className = 'otu-sector-row';
            row.style.cssText = [
                'display:flex', 'align-items:center', 'gap:8px',
                'padding:6px 10px', 'border-radius:4px',
                'border-left:3px solid transparent',
                'cursor:pointer', 'transition:background 0.15s, border-color 0.15s',
                'background:#0d1117'
            ].join(';');

            row.innerHTML = `
                <input type="checkbox" class="otu-sector-check" data-idx="${idx}" checked
                    style="flex-shrink:0; cursor:pointer; accent-color:#66fcf1;">
                <span class="otu-sector-name"
                    style="color:#c5c6c7; font-size:0.85rem; white-space:nowrap;">${sector.name}</span>
                <span class="otu-review otu-review-pending" data-idx="${idx}" title="Checking Traveller Map review status">…</span>
                <span style="flex:1; border-bottom:1px dotted #2a3a3a; margin:0 4px; height:1px; align-self:center;"></span>
                <input type="text" class="otu-sector-slot" value="${sector.defaultSlot}"
                    maxlength="2" size="2"
                    style="width:32px; padding:2px 4px; background:#1f2833; border:1px solid #45a29e;
                           color:#66fcf1; font-family:'Courier New',monospace; font-size:0.85rem;
                           text-align:center; text-transform:uppercase; border-radius:3px;"
                    onclick="event.stopPropagation();">
            `;

            // Highlight row on hover
            row.addEventListener('mouseenter', () => {
                row.style.background = '#1a2535';
                row.style.borderLeftColor = '#45a29e';
            });
            row.addEventListener('mouseleave', () => {
                row.style.background = '#0d1117';
                row.style.borderLeftColor = 'transparent';
            });

            list.appendChild(row);
        });

        // Reset select-all to checked
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) selectAll.checked = true;

        document.getElementById('otu-import-modal').style.display = 'flex';
    }

    /** Close the modal. */
    function closeModal() {
        document.getElementById('otu-import-modal').style.display = 'none';
    }

    /**
     * Pre-flight check, then fetch and import each selected sector in sequence.
     */
    async function runImport() {
        const opts = readImportOptions('otu-opt-sector', 'otu-opt-routes', 'otu-opt-borders', 'otu-opt-regions');
        opts.importSystemData = document.getElementById('otu-opt-system-data')?.checked ?? false;
        const needsMeta = opts.importRoutes || opts.importBorders || opts.importRegions;

        const rows = document.querySelectorAll('.otu-sector-row');
        const selected = [];

        const sectors = getImperiumSectors();
        rows.forEach((row, idx) => {
            const cb = row.querySelector('.otu-sector-check');
            const slotInput = row.querySelector('.otu-sector-slot');
            const slot = (slotInput ? slotInput.value.trim() : '').toUpperCase();
            if (cb && cb.checked && slot) {
                selected.push({ name: sectors[idx].name, slot });
            }
        });

        if (selected.length === 0) {
            alert('No sectors selected.');
            return;
        }

        closeModal();

        // A multi-sector import is a new-document operation, not an edit.
        //
        // It replaces whole sectors — tens of thousands of hexes — and takes no
        // history snapshot of its own. That used to leave whatever snapshot
        // happened to be on top of the undo stack sitting there untouched, so
        // Ctrl+Z afterwards LOOKED like it undid the import (the imported hexes
        // did disappear) while actually restoring a much older state and silently
        // discarding editing done before the import. Measured 2026-09-01: with two
        // ordinary edits made beforehand, one was reverted by an undo the user
        // would reasonably read as "undo the import".
        //
        // Taking a snapshot instead was considered and rejected: a pre-import copy
        // of hexStates is precisely the size the undo cap — already down to 5
        // snapshots on large grids — exists to avoid. So this matches
        // executeUniverseImport(), which has cleared the stacks all along for the
        // same reason.
        //
        // Cleared BEFORE the work rather than after, so an import that fails
        // partway through cannot leave a stale snapshot behind either.
        window.undoStack = [];
        window.redoStack = [];

        // Fetch and import one sector at a time. Each sector makes two API calls
        // (TSV then metadata) with a 1-second pause between each live call.
        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));

        opts.allegianceNames = {};
        let reviewByCoord = null;
        try { reviewByCoord = await loadSectorReview(); } catch (e) { reviewByCoord = null; }
        if (Date.now() - reviewLiveAt < 1000) await delay(1000 - (Date.now() - reviewLiveAt));
        const allegFetch = await fetchAllegianceNames();
        Object.assign(opts.allegianceNames, allegFetch.names);
        if (allegFetch.live) await delay(1000);

        // Build coord lookup for cross-sector route resolution.
        // Only include sectors the user actually imported — pre-loading all sectors
        // caused routes to unimported neighbours to resolve to wrong hexIds on canvas.
        const coordLookup = new Map();
        selected.forEach(sel => {
            const match = sectors.find(s => s.name === sel.name);
            if (match) coordLookup.set(`${match.x},${match.y}`, sectorSlotToNumber(sel.slot));
        });

        const sectorMetas  = [];
        const metaFailures = [];
        for (let i = 0; i < selected.length; i++) {
            const { name, slot } = selected[i];
            let tsvFromCache = false;

            if (opts.importSector) {
                try {
                    clearSectorSlotData(sectorSlotToNumber(slot));

                    const cached = getCachedSector(name);
                    tsvFromCache = cached !== null;

                    if (typeof showToast === 'function') {
                        const source = tsvFromCache ? 'cache' : `API (${i + 1} of ${selected.length})`;
                        showToast(`Importing ${name} into Slot ${slot}… [${source}]`);
                    }

                    const text = tsvFromCache ? cached : await fetchAndCacheSector(name);

                    // bulkMode=true: skip the per-sector rule re-application,
                    // allegiance scan, draw and DB write — those are done once after
                    // the loop. NOT saveHistoryState: this comment used to promise a
                    // deferred snapshot "done once after the loop" that was never
                    // written, and the post-loop block does no history save. A bulk
                    // import is deliberately not undoable — see where the undo stacks
                    // are cleared, above.
                    if (typeof importT5Tab === 'function') {
                        importT5Tab(text, name, slot, true);
                    } else {
                        throw new Error('importT5Tab not available');
                    }

                    // Always use the full name from IMPERIUM_SECTORS (importT5Tab sets an abbreviation)
                    const slotNum = parseInt(slot, 10);
                    if (!isNaN(slotNum)) {
                        window.sectorNames[slotNum] = name;
                        const placed = sectors.find(s => s.name === name);
                        if (placed) rememberSectorReview(slotNum, placed.x, placed.y, reviewByCoord);
                    }
                } catch (err) {
                    alert(`Failed to import "${name}": ${err.message}`);
                }

                // Pause before metadata fetch if TSV came from a live API call.
                if (!tsvFromCache) await delay(1000);
            }

            if (needsMeta) {
                // Fetch and cache metadata now, but defer parsing until all sectors are loaded.
                const sectorInfo = sectors.find(s => s.name === name);
                let metaXml = getCachedMetadata(name);
                if (!metaXml) {
                    if (typeof showToast === 'function') showToast(`Fetching metadata for ${name}…`);
                    metaXml = await fetchAndCacheMetadata(name, sectorInfo?.x, sectorInfo?.y);
                    if (i < selected.length - 1) await delay(1000);
                }
                if (metaXml && sectorInfo) {
                    sectorMetas.push({ name, metaXml, slotNum: sectorSlotToNumber(slot), x: sectorInfo.x, y: sectorInfo.y });
                } else if (!metaXml) {
                    metaFailures.push(name);
                }
            }
        }

        if (needsMeta) {
            // Wipe the X-boat slot and any allegiance slots this import owns.
            // Trade routes and hand-drawn slots stay.
            if (opts.importRoutes && window.sectorRoutes) {
                window.sectorRoutes = window.sectorRoutes.filter(r =>
                    r.routeId !== 1 && !(r.groupId && String(r.groupId).startsWith('otu-route:')));
            }

            // Parse all routes/borders in a single pass after every sector is loaded,
            // so cross-sector routes can resolve both endpoints correctly.
            // Yield between sectors to keep the tab responsive.
            if (typeof parseAndAddOtuRoutes === 'function') {
                for (const m of sectorMetas) {
                    parseAndAddOtuRoutes(m.name, m.metaXml, m.slotNum, m.x, m.y, coordLookup, opts);
                    await delay(0);
                }
            }
            if (window.dbManager) window.dbManager.saveSubsectorNames?.();
            if (opts.importRoutes) {
                if (typeof window.ensureFreeRouteSlot === 'function') window.ensureFreeRouteSlot();
                if (window.dbManager) {
                    window.dbManager.saveRouteDefinitions?.();
                    window.dbManager.saveRoutes?.();
                }
                if (typeof window.renderRouteWindow === 'function') window.renderRouteWindow();
            }
            if (typeof window.sortAndTrimBorderDefinitions === 'function') window.sortAndTrimBorderDefinitions();
            if (typeof window.renderBorderWindow === 'function') window.renderBorderWindow();
        }

        applyAllegianceNames(opts.allegianceNames);

        // Post-processing deferred from bulkMode importT5Tab calls — run once here,
        // after allegiance names have been written onto the hexes.
        if (opts.importSector) {
            if (typeof window.reapplyAllRules === 'function') window.reapplyAllRules();
            if (typeof window.applyActiveFilters === 'function') window.applyActiveFilters();
            if (window.dbManager) window.dbManager.syncAllHexes();
            if (window.dbManager) window.dbManager.saveSectorNames();
            if (window.dbManager) window.dbManager.saveSectorReview?.();
        }

        if (opts.importSystemData && typeof applyOtuSystemData === 'function') {
            applyOtuSystemData();
        }

        requestAnimationFrame(draw);

        if (metaFailures.length > 0 && typeof showToast === 'function') {
            const preview = metaFailures.slice(0, 3).join(', ') + (metaFailures.length > 3 ? `… (+${metaFailures.length - 3} more)` : '');
            showToast(`${metaFailures.length} metadata fetch(es) failed (no borders/routes): ${preview}`, 6000);
            console.warn(`[Imperium Import] Metadata fetch failed for: ${metaFailures.join(', ')}`);
        }

        if (opts.importSector && typeof window.startBackgroundMgtBuild === 'function') {
            window.startBackgroundMgtBuild({
                sectors: selected.map(sel => ({ key: sectorSlotToNumber(sel.slot), name: sel.name }))
            });
        }
    }

    // =========================================================================
    // IMPORT THE UNIVERSE
    // =========================================================================

    function getUniverseSectors() {
        if (!window.UNIVERSE_SECTORS || window.UNIVERSE_SECTORS.length === 0) {
            throw new Error('Universe sector list not loaded. Run convert_universe.ps1 to generate js/universe_data.js.');
        }
        return window.UNIVERSE_SECTORS;
    }

    /** Open the Universe import modal, pre-filling the sector count. */
    function openUniverseModal() {
        let sectors;
        try {
            sectors = getUniverseSectors();
        } catch (err) {
            alert(`Cannot import: ${err.message}`);
            return;
        }
        const countEl = document.getElementById('universe-modal-sector-count');
        if (countEl) countEl.textContent = sectors.length;
        document.getElementById('universe-import-modal').style.display = 'flex';
        fillUniverseReview(sectors);
    }

    /** Close the Universe import modal. */
    function closeUniverseModal() {
        document.getElementById('universe-import-modal').style.display = 'none';
    }

    /**
     * Bulk-imports every sector in UNIVERSE_SECTORS into a freshly resized 16×8 canvas.
     * Called after the user confirms in the modal. Clears all existing data.
     */
    async function executeUniverseImport(opts) {
        const needsMeta = opts.importRoutes || opts.importBorders || opts.importRegions;

        let sectors;
        try {
            sectors = getUniverseSectors();
        } catch (err) {
            alert(`Cannot import: ${err.message}`);
            return;
        }

        // Wipe IndexedDB before clearing memory so no stale data remains.
        if (window.dbManager) await window.dbManager.clearDB();

        // Resize canvas to 16×8 and clear all in-memory state (mirrors clearCanvas).
        gridWidth  = 16;
        gridHeight = 8;
        hexStates.clear();
        window.sectorNames        = {};
        window.sectorReview       = {};
        window.subsectorNames     = {};
        window.sectorRoutes       = [];
        window.routeDefinitions   = (typeof getDefaultRouteDefinitions === 'function') ? getDefaultRouteDefinitions() : [];
        window.undoStack          = [];
        window.redoStack          = [];
        selectedHexes.clear();
        window.hexBorderAssignments = new Map();
        window.borderPaths          = new Map();
        window.regionPaths          = new Map();
        window.borderDefinitions    = (typeof getDefaultBorderDefinitions === 'function') ? getDefaultBorderDefinitions() : [];
        window.regionDefinitions    = (typeof getDefaultRegionDefinitions === 'function') ? getDefaultRegionDefinitions() : [];

        centerCameraOnGrid();
        requestAnimationFrame(draw);

        // Persist the new grid dimensions immediately.
        if (window.dbManager) window.dbManager.saveGridDimensions();

        const delay = (ms) => new Promise(resolve => setTimeout(resolve, ms));
        let errorCount = 0;

        opts.allegianceNames = {};
        let reviewByCoord = null;
        try { reviewByCoord = await loadSectorReview(); } catch (e) { reviewByCoord = null; }
        if (Date.now() - reviewLiveAt < 1000) await delay(1000 - (Date.now() - reviewLiveAt));
        const allegFetch = await fetchAllegianceNames();
        Object.assign(opts.allegianceNames, allegFetch.names);
        if (allegFetch.live) await delay(1000);

        // Build coord lookup from all universe sectors using their default slots.
        const coordLookup = new Map();
        sectors.forEach(s => coordLookup.set(`${s.x},${s.y}`, parseInt(s.defaultSlot, 10)));

        const universeMetas = [];
        const metaFailures = [];
        for (let i = 0; i < sectors.length; i++) {
            const { name, defaultSlot, x, y } = sectors[i];
            let tsvFromCache = false;

            const isMixonForeven = opts.mixonForeven && name === 'Foreven';

            if (opts.importSector) {
                try {
                    if (isMixonForeven) {
                        // Use the embedded JS constant — no fetch needed (avoids CORS on file://).
                        if (!window.FOREVEN_MIXON_TSV) throw new Error('FOREVEN_MIXON_TSV not loaded. Run convert_foreven_mixon.ps1.');
                        tsvFromCache = true; // treat as always-available, no API delay needed

                        if (typeof showToast === 'function') {
                            showToast(`Importing Foreven (Mixon) into Slot ${defaultSlot}… [embedded]`);
                        }

                        const text = window.FOREVEN_MIXON_TSV;

                        if (typeof importT5Tab === 'function') {
                            importT5Tab(text, 'Foreven', defaultSlot, true);
                        } else {
                            throw new Error('importT5Tab not available');
                        }

                        const slotNum = parseInt(defaultSlot, 10);
                        if (!isNaN(slotNum)) {
                            window.sectorNames[slotNum] = 'Foreven';
                            rememberSectorReview(slotNum, x, y, reviewByCoord);
                        }
                    } else {
                        const cached = await getCachedUniverseSector(name);
                        tsvFromCache = cached !== null;

                        if (typeof showToast === 'function') {
                            const source = tsvFromCache ? 'cache' : `API (${i + 1} of ${sectors.length})`;
                            showToast(`Importing ${name} into Slot ${defaultSlot}… [${source}]`);
                        }

                        const text = tsvFromCache ? cached : await fetchAndCacheUniverseSector(name);

                        // bulkMode=true: skip the per-sector rule re-application,
                        // allegiance scan, draw and DB write — those are done once after
                        // the loop. NOT saveHistoryState: this comment used to promise a
                        // deferred snapshot "done once after the loop" that was never
                        // written, and the post-loop block does no history save. A bulk
                        // import is deliberately not undoable — see where the undo stacks
                        // are cleared, above.
                        if (typeof importT5Tab === 'function') {
                            importT5Tab(text, name, defaultSlot, true);
                        } else {
                            throw new Error('importT5Tab not available');
                        }

                        const slotNum = parseInt(defaultSlot, 10);
                        if (!isNaN(slotNum)) {
                            window.sectorNames[slotNum] = name;
                            rememberSectorReview(slotNum, x, y, reviewByCoord);
                        }
                    }
                } catch (err) {
                    console.warn(`[Universe Import] Failed to import "${name}": ${err.message}`);
                    errorCount++;
                }

                // Pause before metadata fetch only for live API calls (not local or cached).
                if (!tsvFromCache && !isMixonForeven) await delay(1000);
            }

            if (needsMeta) {
                if (isMixonForeven) {
                    // Use the locally embedded XML instead of travellermap metadata.
                    if (window.FOREVEN_MIXON_XML) {
                        universeMetas.push({ name: 'Foreven', metaXml: window.FOREVEN_MIXON_XML, slotNum: parseInt(defaultSlot, 10), x, y });
                    }
                } else {
                // Fetch and cache metadata, but defer parsing until all sectors are loaded.
                let metaXml = await getCachedUniverseMetadata(name);
                if (!metaXml) {
                    if (typeof showToast === 'function') showToast(`Fetching metadata for ${name}…`);
                    metaXml = await fetchAndCacheUniverseMetadata(name, x, y);
                    if (i < sectors.length - 1) await delay(1000);
                }
                if (metaXml) {
                    universeMetas.push({ name, metaXml, slotNum: parseInt(defaultSlot, 10), x, y });
                } else if (needsMeta) {
                    metaFailures.push(name);
                }
                } // end else (not isMixonForeven)
            }
        }

        if (needsMeta && typeof parseAndAddOtuRoutes === 'function') {
            // Parse all routes/borders in a single pass after every sector is loaded,
            // so cross-sector routes can resolve both endpoints correctly.
            // Yield to the browser between sectors to keep the tab responsive.
            if (typeof showToast === 'function') showToast(`Processing metadata for ${universeMetas.length} sectors…`);
            for (const m of universeMetas) {
                parseAndAddOtuRoutes(m.name, m.metaXml, m.slotNum, m.x, m.y, coordLookup, opts);
                await delay(0);
            }
            if (window.dbManager) window.dbManager.saveSubsectorNames?.();
            if (opts.importRoutes) {
                if (typeof window.ensureFreeRouteSlot === 'function') window.ensureFreeRouteSlot();
                if (window.dbManager) {
                    window.dbManager.saveRouteDefinitions?.();
                    window.dbManager.saveRoutes?.();
                }
                if (typeof window.renderRouteWindow === 'function') window.renderRouteWindow();
            }
            if (typeof window.sortAndTrimBorderDefinitions === 'function') window.sortAndTrimBorderDefinitions();
            if (typeof window.renderBorderWindow === 'function') window.renderBorderWindow();
        }

        applyAllegianceNames(opts.allegianceNames);

        // Post-processing deferred from bulkMode importT5Tab calls — run once here,
        // after allegiance names have been written onto the hexes.
        if (opts.importSector) {
            if (typeof window.reapplyAllRules === 'function') window.reapplyAllRules();
            if (typeof window.applyActiveFilters === 'function') window.applyActiveFilters();
            if (window.dbManager) window.dbManager.syncAllHexes();
            if (window.dbManager) window.dbManager.saveSectorNames();
            if (window.dbManager) window.dbManager.saveSectorReview?.();
        }

        if (typeof window.renderBorderWindow === 'function') window.renderBorderWindow();
        if (typeof window.renderRegionWindow === 'function') window.renderRegionWindow();

        if (opts.importSystemData && typeof applyOtuSystemData === 'function') {
            applyOtuSystemData();
        }

        requestAnimationFrame(draw);

        if (opts.importSector && typeof window.startBackgroundMgtBuild === 'function') {
            window.startBackgroundMgtBuild({
                sectors: sectors.map(s => ({ key: parseInt(s.defaultSlot, 10), name: s.name }))
            });
        }

        let summary = errorCount > 0
            ? `Universe import complete. ${errorCount} sector(s) failed — see console for details.`
            : `Universe import complete! ${sectors.length} sector(s) loaded.`;
        if (metaFailures.length > 0) {
            const preview = metaFailures.slice(0, 3).join(', ') + (metaFailures.length > 3 ? `… (+${metaFailures.length - 3} more)` : '');
            summary += ` ${metaFailures.length} metadata fetch(es) failed (no borders/routes): ${preview}`;
            console.warn(`[Universe Import] Metadata fetch failed for: ${metaFailures.join(', ')}`);
        }
        if (typeof showToast === 'function') showToast(summary, 6000);
    }

    /** Wire up all event listeners once the DOM is ready. */
    document.addEventListener('DOMContentLoaded', () => {
        // "Import the Imperium" settings button
        const btnImperium = document.getElementById('btn-import-imperium');
        if (btnImperium) {
            btnImperium.addEventListener('click', openImperiumModal);
        }

        // "Import the Universe" settings button — opens modal
        const btnUniverse = document.getElementById('btn-import-universe');
        if (btnUniverse) {
            btnUniverse.addEventListener('click', openUniverseModal);
        }

        // Universe modal: Submit
        const btnUniverseSubmit = document.getElementById('universe-submit');
        if (btnUniverseSubmit) {
            btnUniverseSubmit.addEventListener('click', () => {
                const mixonEl = document.getElementById('universe-opt-mixon-foreven');
                const systemDataEl = document.getElementById('universe-opt-system-data');
                closeUniverseModal();
                executeUniverseImport({
                    importSector:     true,
                    importRoutes:     true,
                    importBorders:    true,
                    importRegions:    true,
                    mixonForeven:     mixonEl ? mixonEl.checked : false,
                    importSystemData: systemDataEl ? systemDataEl.checked : false,
                });
            });
        }

        // Universe modal: Cancel
        const btnUniverseCancel = document.getElementById('universe-cancel');
        if (btnUniverseCancel) {
            btnUniverseCancel.addEventListener('click', closeUniverseModal);
        }

        // Universe modal: backdrop click closes it
        const universeModal = document.getElementById('universe-import-modal');
        if (universeModal) {
            universeModal.addEventListener('click', (e) => {
                if (e.target === universeModal) closeUniverseModal();
            });
        }

        // Modal: Submit
        const btnSubmit = document.getElementById('otu-submit');
        if (btnSubmit) btnSubmit.addEventListener('click', runImport);

        // Modal: Cancel
        const btnCancel = document.getElementById('otu-cancel');
        if (btnCancel) btnCancel.addEventListener('click', closeModal);

        // Modal: Select / Deselect All
        const selectAll = document.getElementById('otu-select-all');
        if (selectAll) {
            selectAll.addEventListener('change', (e) => {
                document.querySelectorAll('.otu-sector-check').forEach(cb => {
                    cb.checked = e.target.checked;
                });
            });
        }

        // Close modal on backdrop click
        const modal = document.getElementById('otu-import-modal');
        if (modal) {
            modal.addEventListener('click', (e) => {
                if (e.target === modal) closeModal();
            });
        }
    });

    // Expose for debugging
    window.openImperiumModal = openImperiumModal;

}());
